/*
 * OBC_CANinterface.h
 *
 *  Created on: Jan 15, 2023
 *      Author: kanhu
 */

#ifndef OBC_CANINTERFACE_H_
#define OBC_CANINTERFACE_H_

#include "vcuSys.h"


//Autonomous mode abort reason codes
#define WATCHDOG_TIMER_OVERFLOWED 10
#define STATUS_MISSED_COUNTER_OVERFLOWED 11
#define USER_PRESSED_THROTTLE 12
#define USER_CHANGED_FNR_STATE 13
#define USER_PRESSED_FOOT_BRAKE 14
#define USER_ACTIVATED_HAND_BRAKE 15
#define ABORTED_BY_USER 30
#define USER_PRESSED_EMERGENCY_STOP 31


//Threshold values
#define MOTOR_RPM_THRESHOLD_FOR_SWITCHING_TO_AUTONOMOUS	 			10
#define THROTTLE_INPUT_THRESHOLD_FOR_SWITCHING_TO_AUTONOMOUS 		3
#define THROTTLE_PRESS_INTERRUPT_THRESHOLD							3
#define HIGHEST_FORWARD_RPM_IN_AUTO_MODE  							3000  //In RPM
#define HIGHEST_REVERSE_RPM_IN_AUTO_MODE  							1500  //In RPM


#define OBC_WATCHDOG_TIMER_THRESHOLD 				500
#define OBC_STATUS_COMM_MISSED_THRESHOLD 			2
#define OBC_STATUS_CHECK_LISTEN_TIMER_THRESHOLD 	500
#define OBC_STATUS_CHECK_INTERVAL 					200
#define OBC_AUTOMODE_REQUEST_TIMEOUT_THRESHOLD 		200


//OBCC request rejection reason codes
#define MOTOR_RPM_ABOVE_THRESHOLD 1
#define THROTTLE_INPUT_ABOVE_THRESHOLD 2
#define AUTOMODE_REQUEST_TIMEOUT 3
#define FOOT_BRAKE_ACTIVE 4
#define HAND_BRAKE_ACTIVE 5
#define EMERGENCY_STOP_ACTIVE 6


typedef enum
{
	OBC_NO_APPROPRIATE_MSG = -1,
	OBC_NO_EVENT = 0,
	OBC_HANDSHAKE_INITIATED = 1,
	OBC_HANDSHAKE_INIT_REQUEST_DENIED = 2,
	OBC_HANDSHAKE_TIMEOUT = 3,
	OBC_HANDSHAKE_SUCCESSFUL = 4,

	OBC_DRIVE_COMMAND_DATA_RECEIVED = 5,
	OBC_STATUS_CHECK_INITIATED = 6,
	OBC_STATUS_CHECK_RESPONSE_RECEIVED = 7,

	OBC_AUTOMODE_TERMINATED_BY_USER = -2,
	OBC_WATCHDOG_TIMEOUT = -3,
	OBC_STATUS_CHECK_UNRESPONSIVE = -4,
	OBC_USER_INTERRUPTED = -5


}OBCinterfaceStatus_t;

OBCinterfaceStatus_t OBC_CANinterface(genericCANframeData_t *CANdataFromOBC, vcuSysState_t *vcuStateData, uint32_t timestamp);

OBCinterfaceStatus_t OBCwatchdog(vcuSysState_t *currentVcuStateData, uint32_t timestamp);


#endif /* OBC_CANINTERFACE_H_ */
