/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC_THROTTLE.h
**     Project     : Boson_VCU_MPC5775B_Z7_0
**     Processor   : MPC5775B_416
**     Component   : adc_pal
**     Version     : Component SDK_S32_PA_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-01-19, 15:59, # CodeGen: 0
**     Contents    :
**         ADC_Init                   - status_t ADC_Init(const adc_instance_t * const instance, const adc_config_t *...
**         ADC_Deinit                 - status_t ADC_Deinit(const adc_instance_t * const instance);
**         ADC_EnableHardwareTrigger  - status_t ADC_EnableHardwareTrigger(const adc_instance_t * const instance,...
**         ADC_DisableHardwareTrigger - status_t ADC_DisableHardwareTrigger(const adc_instance_t * const instance,...
**         ADC_StartGroupConversion   - status_t ADC_StartGroupConversion(const adc_instance_t * const instance,...
**         ADC_StopGroupConversion    - status_t ADC_StopGroupConversion(const adc_instance_t * const instance, const...
**         ADC_EnableNotification     - status_t ADC_EnableNotification(const adc_instance_t * const instance, const...
**         ADC_DisableNotification    - status_t ADC_DisableNotification(const adc_instance_t * const instance, const...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file ADC_THROTTLE.h
** @version 01.00
*/         
/*!
**  @addtogroup ADC_THROTTLE_module ADC_THROTTLE module documentation
**  @{
*/         

#ifndef ADC_THROTTLE_H
#define ADC_THROTTLE_H
/* MODULE ADC_THROTTLE. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, global macro not referenced
 * There are global macros defined to be used by the integrator and another one used as include guard.
 */

/* Include inherited beans */
#include "dmaController1.h"
#include "Cpu.h"
#include "adc_pal.h"


/*! @brief PAL instance information */
extern const adc_instance_t ADC_THROTTLE_instance;


/*! @brief Configuration structure 0 */
extern const adc_config_t ADC_Throttle_InitConfig0;

/*! @brief config 0 group configurations array */
extern const adc_group_config_t ADC_THROTTLE_GroupArray0[1u];

/*! @brief config 0 group 0 channel configuration array  */
extern adc_input_chan_t ADC_THROTTLE_ChansArray00[2u];
/*! @brief config 0 group 0 results buffer */
extern uint16_t ADC_THROTTLE_Results00[(2u) * (2u)];
/*! @brief config 0 group 0 callback function */
extern void throttleADCcallbackFunc(const adc_callback_info_t * const callbackInfo, void * userData);


#endif /* ADC_THROTTLE_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

