/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC_THROTTLE.c
**     Project     : Boson_VCU_MPC5775B_Z7_0
**     Processor   : MPC5775B_416
**     Component   : adc_pal
**     Version     : Component SDK_S32_PA_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-01-19, 15:59, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file ADC_THROTTLE.c
** @version 01.00
*/         
/*!
**  @addtogroup ADC_THROTTLE_module ADC_THROTTLE module documentation
**  @{
*/         

/* MODULE ADC_THROTTLE. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.9, Could define variable at block scope.
 * The external variables will be used in other source files, with the same initialized values.
 */ 

#include <stddef.h>
#include "ADC_THROTTLE.h"

/*! @brief PAL instance information */

const adc_instance_t ADC_THROTTLE_instance = { ADC_INST_TYPE_EQADC, 0u };

/*! @brief Configuration 0 declaration */

static extension_eqadc_t ADC_THROTTLE_Extension0 = {
    .digitalFilterLen   = 0,
    .clkPrescale        = EQADC_PRESCALE_NOT_USED,
    .clkOddPrescaleEn   = false,
    .clkDutySel         = false,
    .samplingTime       = EQADC_SAMPLING_TIME_2_CYCLES,
    .signEn             = false,
};

const adc_config_t ADC_Throttle_InitConfig0 = {
    .sampleTicks        = 0,
    .numGroups          = 1,
    .groupConfigArray   = ADC_THROTTLE_GroupArray0,
    .extension          = &ADC_THROTTLE_Extension0
};

const adc_group_config_t ADC_THROTTLE_GroupArray0[1u] = {
    /* Conversion group 0 */
    {
        ADC_THROTTLE_ChansArray00,     /* inputChannelArray */
        ADC_THROTTLE_Results00,        /* resultBuffer */
        2,     /* numChannels */
        2,     /* numSetsResultBuffer */
        false,        /* hwTriggerSupport */
        ADC_TRIGGER_SOURCE(ADC_TRIG_SOURCE_MODE_RISING_EDGE, 1u),     /* triggerSource */
        ADC_DELAY_TYPE_NO_DELAY,      /* delayType */
        NULL,       /* delayArray */
        false,     /* continuousConvEn */
        throttleADCcallbackFunc,       /* callback */
        NULL        /* callbackUserData */
    },
};

adc_input_chan_t ADC_THROTTLE_ChansArray00[2u] = {
        ADC_CHAN_MAP(0u, 4u),
        ADC_CHAN_MAP(0u, 11u),
};
uint16_t ADC_THROTTLE_Results00[(2u) * (2u)];


/* END ADC_THROTTLE. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
