/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : HSD_SPIB.c
**     Project     : Boson_VCU_MPC5775B_Z7_0
**     Processor   : MPC5775B_416
**     Component   : dspi
**     Version     : Component SDK_S32_PA_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-01-19, 15:59, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file HSD_SPIB.c
** @version 01.00
*/         
/*!
**  @addtogroup HSD_SPIB_module HSD_SPIB module documentation
**  @{
*/         

/*
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * This structure is defined for usage by application code.
 *
 */
 
#include "HSD_SPIB.h"

/*Define state structure for current DSPI instance */
dspi_state_t HSD_SPIBState; 
/* SPI Master Configurations */
dspi_master_config_t HSD_SPIB_MasterInitConfig0 =
{
    .bitsPerSec              = 500000,
    .pcsPolarity             = DSPI_ACTIVE_LOW,
    .bitcount                = 16,
    .clkPhase                = DSPI_CLOCK_PHASE_2ND_EDGE,
    .clkPolarity             = DSPI_ACTIVE_HIGH,
    .lsbFirst                = false,
    .transferType            = DSPI_USING_INTERRUPTS,
    .rxDMAChannel            = 255U,
    .txDMAChannel            = 255U,
    .txAdditionalDMAChannel  = 255U,
    .callback                = NULL,
    .callbackParam           = NULL,
    .continuousPCS           = false,
    .isClkContinuous         = false,
    .whichPCS                = 0
};
 
/* SPI Slave Configurations */
        
/* END HSD_SPIB. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/


