/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : MCAN0.h
**     Project     : Boson_VCU_MPC5775B_Z7_0
**     Processor   : MPC5775B_416
**     Component   : mcan
**     Version     : Component SDK_S32_PA_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-01-19, 15:59, # CodeGen: 0
**     Contents    :
**         MCAN_DRV_Init                  - status_t MCAN_DRV_Init(uint8_t instance,mcan_state_t * state,const...
**         MCAN_DRV_ConfigTxMb            - status_t MCAN_DRV_ConfigTxMb(uint8_t instance,uint8_t mb_idx,const...
**         MCAN_DRV_Send                  - status_t MCAN_DRV_Send(uint8_t instance,uint8_t mb_idx,const mcan_data_info_t...
**         MCAN_DRV_SendBlocking          - status_t MCAN_DRV_SendBlocking(uint8_t instance,uint8_t mb_idx,const...
**         MCAN_DRV_ConfigRxMb            - status_t MCAN_DRV_ConfigRxMb(uint8_t instance,uint8_t mb_idx,const...
**         MCAN_DRV_Receive               - status_t MCAN_DRV_Receive(uint8_t instance,uint8_t mb_idx,mcan_msgbuff_t *...
**         MCAN_DRV_ReceiveBlocking       - status_t MCAN_DRV_ReceiveBlocking(uint8_t instance,uint8_t...
**         MCAN_DRV_InstallEventCallback  - void MCAN_DRV_InstallEventCallback(uint8_t instance,mcan_callback_t...
**         MCAN_DRV_InstallErrorCallback  - void MCAN_DRV_InstallErrorCallback(uint8_t instance,mcan_error_callback_t...
**         MCAN_DRV_Deinit                - status_t MCAN_DRV_Deinit(uint8_t instance);
**         MCAN_DRV_ConfigRxFifo          - status_t MCAN_DRV_ConfigRxFifo(uint8_t instance,mcan_id_table_t *const *...
**         MCAN_DRV_GetTransferStatus     - status_t MCAN_DRV_GetTransferStatus(uint8_t instance,mode_type_t type,uint8_t...
**         MCAN_DRV_RxFifo                - status_t MCAN_DRV_RxFifo(uint8_t instance,uint8_t fifo,mcan_msgbuff_t * data);
**         MCAN_DRV_RxFifoBlocking        - status_t MCAN_DRV_RxFifoBlocking(uint8_t instance,uint8_t fifo,mcan_msgbuff_t...
**         MCAN_DRV_SetNominalBitrate     - status_t MCAN_DRV_SetNominalBitrate(uint8_t instance,const...
**         MCAN_DRV_SetDataBitrate        - status_t MCAN_DRV_SetDataBitrate(uint8_t instance,const mcan_time_segment_t *...
**         MCAN_DRV_AbortTransfer         - status_t MCAN_DRV_AbortTransfer(uint8_t instance,mode_type_t type,uint8_t...
**         MCAN_DRV_SetRxFifoFilterMask   - status_t MCAN_DRV_SetRxFifoFilterMask(uint8_t instance,mcan_msgbuff_id_type_t...
**         MCAN_DRV_SetGlobalFilterConfig - void MCAN_DRV_SetGlobalFilterConfig(uint8_t instance,nonMatchAccept_t...
**         MCAN_DRV_GetDefaultConfig      - void MCAN_DRV_GetDefaultConfig(mcan_user_config_t * config);
**         MCAN_DRV_GetErrorStatus        - void MCAN_DRV_GetErrorStatus(uint8_t instance,mcan_error_status_t * errors);
**         MCAN_DRV_SetTDCOffset          - status_t MCAN_DRV_SetTDCOffset(uint8_t instance,bool enable,uint8_t...
**         MCAN_DRV_GetBitrate            - void MCAN_DRV_GetBitrate(uint8_t instance,mcan_time_segment_t * bitrate);
**         MCAN_DRV_GetBitrateFD          - void MCAN_DRV_GetBitrateFD(uint8_t instance,mcan_time_segment_t * bitrate);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file MCAN0.h
** @version 01.00
*/         
/*!
**  @addtogroup MCAN0_module MCAN0 module documentation
**  @{
*/         
#ifndef MCAN0_H
#define MCAN0_H
/* MODULE MCAN0. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, global macro not referenced
 * There are global macros defined to be used by the integrator and another one used as include guard.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "mcan_driver.h"

/*! @brief Device instance number */
#define INST_MCAN0 0U


/*! @brief Driver state structure which holds driver runtime data */
extern mcan_state_t MCAN0_State;
 
extern const mcan_id_table_t * MCAN0_mcan_id_table_t0[1];
extern const mcan_id_table_t MCAN0_mcan_id_table_t0_0;


extern const mcan_user_config_t MCAN0_mcan_user_config_t0;

#endif
/* ifndef MCAN0_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
